// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type IeqScores struct {
	DeviceID          string    `json:"deviceId"`
	Timestamp         time.Time `json:"timestamp"`
	Scheme            string    `json:"scheme"`
	Thermal           float64   `json:"thermal"`
	Thermalweighting  float64   `json:"thermalweighting"`
	Iaq               float64   `json:"iaq"`
	Iaqweighting      float64   `json:"iaqweighting"`
	Lighting          float64   `json:"lighting"`
	Lightingweighting float64   `json:"lightingweighting"`
	Noise             float64   `json:"noise"`
	Noiseweighting    float64   `json:"noiseweighting"`
	Overall           float64   `json:"overall"`
}

type MetricScores struct {
	DeviceID    string    `json:"deviceId"`
	Timestamp   time.Time `json:"timestamp"`
	Temperature float64   `json:"temperature"`
	Humidity    float64   `json:"humidity"`
	Co2         float64   `json:"co2"`
	Voc         float64   `json:"voc"`
	Pm25        float64   `json:"pm25"`
	Lighting    float64   `json:"lighting"`
	Noise       float64   `json:"noise"`
}

type Metrics struct {
	DeviceID    string    `json:"deviceId"`
	Timestamp   time.Time `json:"timestamp"`
	Temperature float64   `json:"temperature"`
	Humidity    float64   `json:"humidity"`
	Co2         float64   `json:"co2"`
	Voc         float64   `json:"voc"`
	Pm25        float64   `json:"pm25"`
	Lighting    float64   `json:"lighting"`
	Noise       float64   `json:"noise"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}
